#!/usr/bin/env python3
"""Emit the SQL that loads data/*.json into D1.

    .venv/bin/python scripts/seed_d1.py > worker/seed.sql
    cd worker && npx wrangler d1 execute ccac-sitefinder --file=schema.sql --remote
    cd worker && npx wrangler d1 execute ccac-sitefinder --file=seed.sql   --remote

Seeding is idempotent and non-destructive for anything a human has touched:
candidates are INSERTed and their *discovered* fields refreshed on conflict,
but status, notes, contacts and every hand-entered research field are left
exactly as the committee left them. Re-running the discovery scripts must
never quietly undo somebody's afternoon of phone calls.
"""

from __future__ import annotations

import json
import sys
import uuid
from datetime import datetime, timezone

from common import DATA, read_json

DEFAULT_SETTINGS = {
    # Scoring weights (PRD 7.6). Editable in the UI; these are only the seed.
    "weights": json.dumps({
        "drive_share_20min": 35,
        "capacity_band": 25,
        "availability_evidence": 25,
        "tenancy_type": 15,
    }),
    # Growth scenarios (PRD 7.4a).
    "growth": json.dumps({
        "asa_current": 95,
        "rates": {"conservative": 0.08, "base": 0.12, "surge": 0.20},
        "target_fill": 0.80,
    }),
    "screen": json.dumps({
        "seats_min": 150, "seats_max": 250,
        "seats_favor_min": 175, "seats_favor_max": 225,
        "search_radius_mi": 40,
    }),
}


def q(v) -> str:
    """SQL literal. Everything here is our own generated data, but quote anyway."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main() -> int:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    hh = read_json(DATA / "households_anon.json", {}) or {}
    att = read_json(DATA / "attenders_anon.json", {}) or {}
    cent = read_json(DATA / "centroids.json", {}) or {}
    ch = read_json(DATA / "churches.json", {}) or {}
    iso = read_json(DATA / "isochrones.json", {}) or {}
    drive = read_json(DATA / "candidate_drive.json", {}) or {}
    examples = read_json(DATA / "examples.json", {}) or {}
    dq = read_json(DATA / "data_quality.json", {}) or {}

    lines = [
        "-- Generated by scripts/seed_d1.py. Do not edit by hand.",
        f"-- Generated at {now}",
        "PRAGMA foreign_keys = ON;",
        "BEGIN TRANSACTION;",
        "",
        "-- Anonymous household points are fully derived from the pipeline, so",
        "-- they are replaced wholesale on every seed.",
        "DELETE FROM households_anon;",
    ]
    for h in hh.get("households", []):
        lines.append(
            "INSERT INTO households_anon (id, lat, lon, zip, in_state, outlier, match_quality, corrected) VALUES ("
            + ", ".join(q(h.get(k)) for k in ("id", "lat", "lon", "zip", "in_state", "outlier", "match_quality"))
            + f", {q(h.get('corrected', 0))});"
        )

    lines += ["", "DELETE FROM attenders_anon;"]
    for a in att.get("attenders", []):
        lines.append(
            "INSERT INTO attenders_anon (id, zip, lat, lon, household_size, joined_within_12mo) VALUES ("
            + ", ".join(q(a.get(k)) for k in ("id", "zip", "lat", "lon", "household_size", "joined_within_12mo"))
            + ");"
        )

    lines += ["", "DELETE FROM centroids;"]
    for method, c in (cent.get("centroids") or {}).items():
        meta = {k: v for k, v in c.items() if k not in ("lat", "lon")}
        meta["is_default"] = method == cent.get("default_method")
        lines.append(
            f"INSERT INTO centroids (method, lat, lon, meta_json) VALUES "
            f"({q(method)}, {q(c['lat'])}, {q(c['lon'])}, {q(json.dumps(meta))});"
        )

    iso_center = iso.get("center") or {}
    lines += ["", "-- Isochrones are fully derived, so they are replaced wholesale.",
              "DELETE FROM isochrones;"]
    for feat in iso.get("features", []):
        props = feat.get("properties") or {}
        lines.append(
            "INSERT INTO isochrones (minutes, center_lat, center_lon, method, geojson, cells, "
            "grid_spacing_km, generated_at) VALUES ("
            + ", ".join(q(v) for v in (
                props.get("minutes"), iso_center.get("lat"), iso_center.get("lon"),
                iso_center.get("method"), json.dumps(feat.get("geometry")),
                props.get("cells"), iso.get("grid_spacing_km"), now,
            )) + ");"
        )

    # Examples are fiction and are replaced wholesale; a stale one lingering in
    # the list is exactly the confusion they are labelled to prevent.
    lines += ["", "DELETE FROM candidates WHERE is_example = 1;"]

    lines += ["", "-- Candidates: refresh discovered geometry, preserve human research."]
    for c in list(ch.get("candidates", [])) + list(examples.get("candidates", [])):
        cols = ["id", "name", "denomination", "address", "lat", "lon", "website", "phone",
                "footprint_ft2", "parking_m2", "parking_spaces_est", "parking_lots_counted",
                "parking_shared_suspect", "capacity_est",
                "distance_mi_from_center", "source", "is_example", "tenancy_possible",
                "listed_for_lease", "denomination_notes", "updated_by", "updated_at"]
        vals = [c.get("id"), c.get("name"), c.get("denomination"), c.get("address"),
                c.get("lat"), c.get("lon"), c.get("website"), c.get("phone"),
                c.get("footprint_ft2"), c.get("parking_m2"), c.get("parking_spaces_est"),
                c.get("parking_lots_counted"), c.get("parking_shared_suspect"),
                c.get("capacity_est") or "unknown", c.get("distance_mi_from_center"),
                c.get("source") or "osm", c.get("is_example", 0),
                c.get("tenancy_possible") or "unknown", c.get("listed_for_lease"),
                c.get("denomination_notes"), "pipeline", now]
        lines.append(
            f"INSERT INTO candidates ({', '.join(cols)}) VALUES ({', '.join(q(v) for v in vals)})\n"
            "  ON CONFLICT(id) DO UPDATE SET\n"
            "    name = excluded.name,\n"
            "    denomination = COALESCE(candidates.denomination, excluded.denomination),\n"
            "    address = COALESCE(candidates.address, excluded.address),\n"
            "    lat = excluded.lat, lon = excluded.lon,\n"
            "    website = COALESCE(candidates.website, excluded.website),\n"
            "    phone = COALESCE(candidates.phone, excluded.phone),\n"
            "    footprint_ft2 = excluded.footprint_ft2,\n"
            "    parking_m2 = excluded.parking_m2,\n"
            "    parking_spaces_est = excluded.parking_spaces_est,\n"
            "    parking_lots_counted = excluded.parking_lots_counted,\n"
            "    parking_shared_suspect = excluded.parking_shared_suspect,\n"
            "    distance_mi_from_center = excluded.distance_mi_from_center,\n"
            "    -- a confirmed seat count always outranks the estimated band\n"
            "    capacity_est = CASE WHEN candidates.capacity_confirmed IS NOT NULL\n"
            "                        THEN candidates.capacity_est ELSE excluded.capacity_est END;"
        )

    # Batch-routed drive times. These fill share_hh_within_20min, which the
    # discovery pipeline cannot know and which carries the heaviest scoring
    # weight. Without them every candidate scores zero on drive share, and the
    # sort order that decides which candidates a person ever opens is computed
    # with the most important factor missing.
    drive_rows = drive.get("candidates") or {}
    if drive_rows:
        lines += ["", f"-- Routed drive times for {len(drive_rows)} candidate(s).",
                  "DELETE FROM candidate_drive;"]
        for cid, d in drive_rows.items():
            bands = {k: {"share": v["share"], "count": v["count"]} for k, v in d["bands"].items()}
            lines.append(
                "INSERT INTO candidate_drive (candidate_id, computed_at, source, households, "
                "minutes_json, bands_json, median_min, mean_min) SELECT "
                + ", ".join(q(v) for v in (
                    cid, now, d.get("source") or "osrm", drive.get("households"),
                    json.dumps(d.get("minutes") or {}), json.dumps(bands),
                    d.get("median_min"), d.get("mean_min"),
                ))
                + f" WHERE EXISTS (SELECT 1 FROM candidates WHERE id = {q(cid)});"
            )
            within20 = (d["bands"].get("20") or {}).get("share")
            if within20 is not None:
                lines.append(
                    f"UPDATE candidates SET share_hh_within_20min = {q(within20)}, "
                    f"drive_min_from_center = {q(d.get('median_min'))} WHERE id = {q(cid)};"
                )

    lines += ["", "-- Settings seed only where absent; never clobber edited weights."]
    for k, v in DEFAULT_SETTINGS.items():
        lines.append(f"INSERT OR IGNORE INTO settings (key, value) VALUES ({q(k)}, {q(v)});")

    # The ingest summary has to be carried across, because the rows it counts do
    # not exist in the database. Only households with an address become rows, so
    # the database cannot see the 30 donors who could not be placed at all, and a
    # dashboard counting rows would report "43 of 43" and hide the whole problem.
    if dq:
        lines.append(
            "INSERT INTO settings (key, value) VALUES "
            f"({q('ingest')}, {q(json.dumps(dq))}) "
            "ON CONFLICT(key) DO UPDATE SET value = excluded.value;"
        )

    counts = {
        "households": len(hh.get("households", [])),
        "attenders": len(att.get("attenders", [])),
        "candidates": len(ch.get("candidates", [])),
        "examples": len(examples.get("candidates", [])),
        "centroids": len(cent.get("centroids") or {}),
        "isochrones": len(iso.get("features", [])),
        "candidates_routed": len(drive_rows),
    }
    lines += [
        "",
        "INSERT INTO audit_log (id, actor, action, entity, at, detail) VALUES ("
        + ", ".join(q(v) for v in (
            "seed:" + now + ":" + uuid.uuid4().hex[:8],
            "pipeline", "seed", "database", now, json.dumps(counts),
        )) + ");",
        "COMMIT;",
    ]

    print("\n".join(lines))
    print(
        f"\n-- summary: {len(hh.get('households', []))} households, "
        f"{len(att.get('attenders', []))} attenders, "
        f"{len(cent.get('centroids') or {})} centroids, "
        f"{len(ch.get('candidates', []))} candidates, "
        f"{len(iso.get('features', []))} isochrone bands, "
        f"{len(drive_rows)} routed",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
